[package]
name = "srv1"
version = "0.1.0"
authors = ["Dmitry Shuranov <dvshur@gmail.com>"]
edition = "2018"

[dependencies]
async-trait = "0.1.30"
futures= "0.3"
tokio = { version = "0.2", features = ["full"] }
tonic = "0.2"

[build-dependencies]
tonic-build = "0.2"